sudo: required

env:
  - distribution: centos
    version: 7
    test_role: rhel7-role-rht-ccp

services:
  - docker

language: python
python: "2.7"

install:
  - pip install molecule docker

script:
  - molecule --debug test --scenario-name docker
